#! /bin/bash

cores=`nproc`

for a in ./*.opus; do
    let counter=counter+1

    avconv -n -nostats -loglevel info -i "$a" -codec:a libmp3lame -qscale:a 0 "${a[@]/%opus/mp3}" &

    if [ $counter -gt $cores  ]; then
        wait -n
        let counter=counter-1
    fi
done

